sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "10.15.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run test-headless
  - ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN